/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AttestationBody_H_
#define	_AttestationBody_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttestationVerifierBody.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EXTERNAL;
struct Extension;

/* AttestationBody */
typedef struct AttestationBody {
	AttestationVerifierBody_t	 verifierBody;
	struct AttestationBody__proverPolicyAddendums {
		A_SEQUENCE_OF(struct EXTERNAL) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} proverPolicyAddendums;
	struct AttestationBody__proverExtensions {
		A_SEQUENCE_OF(struct Extension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} proverExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttestationBody_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttestationBody;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EXTERNAL.h"
#include "Extension.h"

#endif	/* _AttestationBody_H_ */
#include <asn_internal.h>
