/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_BN256OAQUEKeyringBundle_H_
#define	_BN256OAQUEKeyringBundle_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Params-BN256-OAQUE.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BN256OAQUEBundleEntry;

/* BN256OAQUEKeyringBundle */
typedef struct BN256OAQUEKeyringBundle {
	Params_BN256_OAQUE_t	 params;
	struct BN256OAQUEKeyringBundle__entries {
		A_SEQUENCE_OF(struct BN256OAQUEBundleEntry) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} entries;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BN256OAQUEKeyringBundle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BN256OAQUEKeyringBundle;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BN256OAQUEBundleEntry.h"

#endif	/* _BN256OAQUEKeyringBundle_H_ */
#include <asn_internal.h>
