/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Capability_H_
#define	_Capability_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Capability {
	Capability_certification	= 1,
	Capability_attestation	= 2,
	Capability_signing	= 3,
	Capability_authentication	= 4,
	Capability_authorization	= 5,
	Capability_encryption	= 6
} e_Capability;

/* Capability */
typedef long	 Capability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Capability;
asn_struct_free_f Capability_free;
asn_struct_print_f Capability_print;
asn_constr_check_f Capability_constraint;
ber_type_decoder_f Capability_decode_ber;
der_type_encoder_f Capability_encode_der;
xer_type_decoder_f Capability_decode_xer;
xer_type_encoder_f Capability_encode_xer;
oer_type_decoder_f Capability_decode_oer;
oer_type_encoder_f Capability_encode_oer;
per_type_decoder_f Capability_decode_uper;
per_type_encoder_f Capability_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Capability_H_ */
#include <asn_internal.h>
