/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CommitmentRevocationOption_H_
#define	_CommitmentRevocationOption_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Hash.h"
#include "Location.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CommitmentRevocationOption */
typedef struct CommitmentRevocationOption {
	Hash_t	 hash;
	Location_t	 location;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CommitmentRevocationOption_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CommitmentRevocationOption;

#ifdef __cplusplus
}
#endif

#endif	/* _CommitmentRevocationOption_H_ */
#include <asn_internal.h>
