/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "EntityPublicKey.h"

static asn_TYPE_member_t asn_MBR_capabilityFlags_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Capability,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_capabilityFlags_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_capabilityFlags_specs_2 = {
	sizeof(struct EntityPublicKey__capabilityFlags),
	offsetof(struct EntityPublicKey__capabilityFlags, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_capabilityFlags_2 = {
	"capabilityFlags",
	"capabilityFlags",
	&asn_OP_SET_OF,
	asn_DEF_capabilityFlags_tags_2,
	sizeof(asn_DEF_capabilityFlags_tags_2)
		/sizeof(asn_DEF_capabilityFlags_tags_2[0]), /* 1 */
	asn_DEF_capabilityFlags_tags_2,	/* Same as above */
	sizeof(asn_DEF_capabilityFlags_tags_2)
		/sizeof(asn_DEF_capabilityFlags_tags_2[0]), /* 1 */
	{ 0, 0, SET_OF_constraint },
	asn_MBR_capabilityFlags_2,
	1,	/* Single element */
	&asn_SPC_capabilityFlags_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_EntityPublicKey_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EntityPublicKey, capabilityFlags),
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_capabilityFlags_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"capabilityFlags"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntityPublicKey, key),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EXTERNAL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"key"
		},
};
static const ber_tlv_tag_t asn_DEF_EntityPublicKey_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EntityPublicKey_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 1, 0, 0 }, /* key */
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 0, 0, 0 } /* capabilityFlags */
};
asn_SEQUENCE_specifics_t asn_SPC_EntityPublicKey_specs_1 = {
	sizeof(struct EntityPublicKey),
	offsetof(struct EntityPublicKey, _asn_ctx),
	asn_MAP_EntityPublicKey_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EntityPublicKey = {
	"EntityPublicKey",
	"EntityPublicKey",
	&asn_OP_SEQUENCE,
	asn_DEF_EntityPublicKey_tags_1,
	sizeof(asn_DEF_EntityPublicKey_tags_1)
		/sizeof(asn_DEF_EntityPublicKey_tags_1[0]), /* 1 */
	asn_DEF_EntityPublicKey_tags_1,	/* Same as above */
	sizeof(asn_DEF_EntityPublicKey_tags_1)
		/sizeof(asn_DEF_EntityPublicKey_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EntityPublicKey_1,
	2,	/* Elements count */
	&asn_SPC_EntityPublicKey_specs_1	/* Additional specs */
};

