/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EntityPrivateKey_H_
#define	_EntityPrivateKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EXTERNAL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EntityPrivateKey */
typedef EXTERNAL_t	 EntityPrivateKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EntityPrivateKey;
asn_struct_free_f EntityPrivateKey_free;
asn_struct_print_f EntityPrivateKey_print;
asn_constr_check_f EntityPrivateKey_constraint;
ber_type_decoder_f EntityPrivateKey_decode_ber;
der_type_encoder_f EntityPrivateKey_encode_der;
xer_type_decoder_f EntityPrivateKey_decode_xer;
xer_type_encoder_f EntityPrivateKey_encode_xer;
oer_type_decoder_f EntityPrivateKey_decode_oer;
oer_type_encoder_f EntityPrivateKey_encode_oer;
per_type_decoder_f EntityPrivateKey_decode_uper;
per_type_encoder_f EntityPrivateKey_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EntityPrivateKey_H_ */
#include <asn_internal.h>
