/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_HashSha3_256_H_
#define	_HashSha3_256_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HashSha3-256 */
typedef OCTET_STRING_t	 HashSha3_256_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HashSha3_256;
asn_struct_free_f HashSha3_256_free;
asn_struct_print_f HashSha3_256_print;
asn_constr_check_f HashSha3_256_constraint;
ber_type_decoder_f HashSha3_256_decode_ber;
der_type_encoder_f HashSha3_256_encode_der;
xer_type_decoder_f HashSha3_256_decode_xer;
xer_type_encoder_f HashSha3_256_encode_xer;
oer_type_decoder_f HashSha3_256_decode_oer;
oer_type_encoder_f HashSha3_256_encode_oer;
per_type_decoder_f HashSha3_256_decode_uper;
per_type_encoder_f HashSha3_256_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HashSha3_256_H_ */
#include <asn_internal.h>
