/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Master_BLS12381_OAQUE_H_
#define	_Master_BLS12381_OAQUE_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Master-BLS12381-OAQUE */
typedef OCTET_STRING_t	 Master_BLS12381_OAQUE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Master_BLS12381_OAQUE;
asn_struct_free_f Master_BLS12381_OAQUE_free;
asn_struct_print_f Master_BLS12381_OAQUE_print;
asn_constr_check_f Master_BLS12381_OAQUE_constraint;
ber_type_decoder_f Master_BLS12381_OAQUE_decode_ber;
der_type_encoder_f Master_BLS12381_OAQUE_encode_der;
xer_type_decoder_f Master_BLS12381_OAQUE_decode_xer;
xer_type_encoder_f Master_BLS12381_OAQUE_encode_xer;
oer_type_decoder_f Master_BLS12381_OAQUE_decode_oer;
oer_type_encoder_f Master_BLS12381_OAQUE_encode_oer;
per_type_decoder_f Master_BLS12381_OAQUE_decode_uper;
per_type_encoder_f Master_BLS12381_OAQUE_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Master_BLS12381_OAQUE_H_ */
#include <asn_internal.h>
