/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "NameDeclarationBody.h"

static asn_TYPE_member_t asn_MBR_validity_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NameDeclarationBody__validity, notBefore),
		(ASN_TAG_CLASS_UNIVERSAL | (23 << 2)),
		0,
		&asn_DEF_UTCTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notBefore"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NameDeclarationBody__validity, notAfter),
		(ASN_TAG_CLASS_UNIVERSAL | (23 << 2)),
		0,
		&asn_DEF_UTCTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notAfter"
		},
};
static const ber_tlv_tag_t asn_DEF_validity_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_validity_tag2el_5[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (23 << 2)), 0, 0, 1 }, /* notBefore */
    { (ASN_TAG_CLASS_UNIVERSAL | (23 << 2)), 1, -1, 0 } /* notAfter */
};
static asn_SEQUENCE_specifics_t asn_SPC_validity_specs_5 = {
	sizeof(struct NameDeclarationBody__validity),
	offsetof(struct NameDeclarationBody__validity, _asn_ctx),
	asn_MAP_validity_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_validity_5 = {
	"validity",
	"validity",
	&asn_OP_SEQUENCE,
	asn_DEF_validity_tags_5,
	sizeof(asn_DEF_validity_tags_5)
		/sizeof(asn_DEF_validity_tags_5[0]), /* 1 */
	asn_DEF_validity_tags_5,	/* Same as above */
	sizeof(asn_DEF_validity_tags_5)
		/sizeof(asn_DEF_validity_tags_5[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_validity_5,
	2,	/* Elements count */
	&asn_SPC_validity_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_privateExtensions_8[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_privateExtensions_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_privateExtensions_specs_8 = {
	sizeof(struct NameDeclarationBody__privateExtensions),
	offsetof(struct NameDeclarationBody__privateExtensions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_privateExtensions_8 = {
	"privateExtensions",
	"privateExtensions",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_privateExtensions_tags_8,
	sizeof(asn_DEF_privateExtensions_tags_8)
		/sizeof(asn_DEF_privateExtensions_tags_8[0]), /* 1 */
	asn_DEF_privateExtensions_tags_8,	/* Same as above */
	sizeof(asn_DEF_privateExtensions_tags_8)
		/sizeof(asn_DEF_privateExtensions_tags_8[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_privateExtensions_8,
	1,	/* Single element */
	&asn_SPC_privateExtensions_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_NameDeclarationBody_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NameDeclarationBody, name),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NameDeclarationBody, subject),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EntityHash,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subject"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NameDeclarationBody, subjectLocation),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_Location,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subjectLocation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NameDeclarationBody, validity),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_validity_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"validity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NameDeclarationBody, privateExtensions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_privateExtensions_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"privateExtensions"
		},
};
static const ber_tlv_tag_t asn_DEF_NameDeclarationBody_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NameDeclarationBody_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 1, 0, 1 }, /* subject */
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 2, -1, 0 }, /* subjectLocation */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 0, 0, 0 }, /* name */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, 0, 1 }, /* validity */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -1, 0 } /* privateExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_NameDeclarationBody_specs_1 = {
	sizeof(struct NameDeclarationBody),
	offsetof(struct NameDeclarationBody, _asn_ctx),
	asn_MAP_NameDeclarationBody_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NameDeclarationBody = {
	"NameDeclarationBody",
	"NameDeclarationBody",
	&asn_OP_SEQUENCE,
	asn_DEF_NameDeclarationBody_tags_1,
	sizeof(asn_DEF_NameDeclarationBody_tags_1)
		/sizeof(asn_DEF_NameDeclarationBody_tags_1[0]), /* 1 */
	asn_DEF_NameDeclarationBody_tags_1,	/* Same as above */
	sizeof(asn_DEF_NameDeclarationBody_tags_1)
		/sizeof(asn_DEF_NameDeclarationBody_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NameDeclarationBody_1,
	5,	/* Elements count */
	&asn_SPC_NameDeclarationBody_specs_1	/* Additional specs */
};

