/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Private_Ed25519_H_
#define	_Private_Ed25519_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Private-Ed25519 */
typedef OCTET_STRING_t	 Private_Ed25519_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Private_Ed25519;
asn_struct_free_f Private_Ed25519_free;
asn_struct_print_f Private_Ed25519_print;
asn_constr_check_f Private_Ed25519_constraint;
ber_type_decoder_f Private_Ed25519_decode_ber;
der_type_encoder_f Private_Ed25519_encode_der;
xer_type_decoder_f Private_Ed25519_decode_xer;
xer_type_encoder_f Private_Ed25519_encode_xer;
oer_type_decoder_f Private_Ed25519_decode_oer;
oer_type_encoder_f Private_Ed25519_encode_oer;
per_type_decoder_f Private_Ed25519_decode_uper;
per_type_encoder_f Private_Ed25519_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Private_Ed25519_H_ */
#include <asn_internal.h>
