/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Public_BN256_IBE_H_
#define	_Public_BN256_IBE_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Params-BN256-IBE.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Public-BN256-IBE */
typedef struct Public_BN256_IBE {
	Params_BN256_IBE_t	 params;
	OCTET_STRING_t	 id;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Public_BN256_IBE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Public_BN256_IBE;

#ifdef __cplusplus
}
#endif

#endif	/* _Public_BN256_IBE_H_ */
#include <asn_internal.h>
