/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Public_OAQUE_H_
#define	_Public_OAQUE_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Params-BN256-OAQUE.h"
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Public-OAQUE */
typedef struct Public_OAQUE {
	Params_BN256_OAQUE_t	 params;
	struct Public_OAQUE__attributeset {
		A_SEQUENCE_OF(OCTET_STRING_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} attributeset;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Public_OAQUE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Public_OAQUE;

#ifdef __cplusplus
}
#endif

#endif	/* _Public_OAQUE_H_ */
#include <asn_internal.h>
