/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RTreeStatement_H_
#define	_RTreeStatement_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EntityHash.h"
#include <UTF8String.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RTreeStatement */
typedef struct RTreeStatement {
	EntityHash_t	 permissionSet;
	struct RTreeStatement__permissions {
		A_SEQUENCE_OF(UTF8String_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} permissions;
	UTF8String_t	 resource;
	UTF8String_t	*comment	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RTreeStatement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RTreeStatement;
extern asn_SEQUENCE_specifics_t asn_SPC_RTreeStatement_specs_1;
extern asn_TYPE_member_t asn_MBR_RTreeStatement_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RTreeStatement_H_ */
#include <asn_internal.h>
