/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "RTreeStatement.h"

static asn_TYPE_member_t asn_MBR_permissions_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_permissions_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_permissions_specs_3 = {
	sizeof(struct RTreeStatement__permissions),
	offsetof(struct RTreeStatement__permissions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_permissions_3 = {
	"permissions",
	"permissions",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_permissions_tags_3,
	sizeof(asn_DEF_permissions_tags_3)
		/sizeof(asn_DEF_permissions_tags_3[0]), /* 1 */
	asn_DEF_permissions_tags_3,	/* Same as above */
	sizeof(asn_DEF_permissions_tags_3)
		/sizeof(asn_DEF_permissions_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_permissions_3,
	1,	/* Single element */
	&asn_SPC_permissions_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RTreeStatement_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RTreeStatement, permissionSet),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EntityHash,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"permissionSet"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RTreeStatement, permissions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_permissions_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"permissions"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RTreeStatement, resource),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"resource"
		},
	{ ATF_POINTER, 1, offsetof(struct RTreeStatement, comment),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"comment"
		},
};
static const int asn_MAP_RTreeStatement_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_RTreeStatement_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RTreeStatement_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 0, 0, 0 }, /* permissionSet */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 2, 0, 1 }, /* resource */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 3, -1, 0 }, /* comment */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 } /* permissions */
};
asn_SEQUENCE_specifics_t asn_SPC_RTreeStatement_specs_1 = {
	sizeof(struct RTreeStatement),
	offsetof(struct RTreeStatement, _asn_ctx),
	asn_MAP_RTreeStatement_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_RTreeStatement_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RTreeStatement = {
	"RTreeStatement",
	"RTreeStatement",
	&asn_OP_SEQUENCE,
	asn_DEF_RTreeStatement_tags_1,
	sizeof(asn_DEF_RTreeStatement_tags_1)
		/sizeof(asn_DEF_RTreeStatement_tags_1[0]), /* 1 */
	asn_DEF_RTreeStatement_tags_1,	/* Same as above */
	sizeof(asn_DEF_RTreeStatement_tags_1)
		/sizeof(asn_DEF_RTreeStatement_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RTreeStatement_1,
	4,	/* Elements count */
	&asn_SPC_RTreeStatement_specs_1	/* Additional specs */
};

