/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SignedOuterKeyTbs_H_
#define	_SignedOuterKeyTbs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignedOuterKeyTbs */
typedef struct SignedOuterKeyTbs {
	OBJECT_IDENTIFIER_t	 outerSignatureScheme;
	OCTET_STRING_t	 verifyingKey;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignedOuterKeyTbs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignedOuterKeyTbs;
extern asn_SEQUENCE_specifics_t asn_SPC_SignedOuterKeyTbs_specs_1;
extern asn_TYPE_member_t asn_MBR_SignedOuterKeyTbs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SignedOuterKeyTbs_H_ */
#include <asn_internal.h>
