/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "SignedOuterKey.h"

static asn_TYPE_member_t asn_MBR_tbs_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SignedOuterKey__tbs, outerSignatureScheme),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"outerSignatureScheme"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignedOuterKey__tbs, verifyingKey),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"verifyingKey"
		},
};
static const ber_tlv_tag_t asn_DEF_tbs_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_tbs_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* verifyingKey */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* outerSignatureScheme */
};
static asn_SEQUENCE_specifics_t asn_SPC_tbs_specs_2 = {
	sizeof(struct SignedOuterKey__tbs),
	offsetof(struct SignedOuterKey__tbs, _asn_ctx),
	asn_MAP_tbs_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tbs_2 = {
	"tbs",
	"tbs",
	&asn_OP_SEQUENCE,
	asn_DEF_tbs_tags_2,
	sizeof(asn_DEF_tbs_tags_2)
		/sizeof(asn_DEF_tbs_tags_2[0]), /* 1 */
	asn_DEF_tbs_tags_2,	/* Same as above */
	sizeof(asn_DEF_tbs_tags_2)
		/sizeof(asn_DEF_tbs_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_tbs_2,
	2,	/* Elements count */
	&asn_SPC_tbs_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SignedOuterKey_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SignedOuterKey, tbs),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_tbs_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tbs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignedOuterKey, signature),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signature"
		},
};
static const ber_tlv_tag_t asn_DEF_SignedOuterKey_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SignedOuterKey_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* signature */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* tbs */
};
static asn_SEQUENCE_specifics_t asn_SPC_SignedOuterKey_specs_1 = {
	sizeof(struct SignedOuterKey),
	offsetof(struct SignedOuterKey, _asn_ctx),
	asn_MAP_SignedOuterKey_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SignedOuterKey = {
	"SignedOuterKey",
	"SignedOuterKey",
	&asn_OP_SEQUENCE,
	asn_DEF_SignedOuterKey_tags_1,
	sizeof(asn_DEF_SignedOuterKey_tags_1)
		/sizeof(asn_DEF_SignedOuterKey_tags_1[0]), /* 1 */
	asn_DEF_SignedOuterKey_tags_1,	/* Same as above */
	sizeof(asn_DEF_SignedOuterKey_tags_1)
		/sizeof(asn_DEF_SignedOuterKey_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SignedOuterKey_1,
	2,	/* Elements count */
	&asn_SPC_SignedOuterKey_specs_1	/* Additional specs */
};

