/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "WaveAttestation.h"

static asn_TYPE_member_t asn_MBR_revocations_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RevocationOption,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_revocations_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_revocations_specs_5 = {
	sizeof(struct WaveAttestation__tbs__revocations),
	offsetof(struct WaveAttestation__tbs__revocations, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_revocations_5 = {
	"revocations",
	"revocations",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_revocations_tags_5,
	sizeof(asn_DEF_revocations_tags_5)
		/sizeof(asn_DEF_revocations_tags_5[0]), /* 1 */
	asn_DEF_revocations_tags_5,	/* Same as above */
	sizeof(asn_DEF_revocations_tags_5)
		/sizeof(asn_DEF_revocations_tags_5[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_revocations_5,
	1,	/* Single element */
	&asn_SPC_revocations_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_publicExtensions_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_publicExtensions_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_publicExtensions_specs_7 = {
	sizeof(struct WaveAttestation__tbs__publicExtensions),
	offsetof(struct WaveAttestation__tbs__publicExtensions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_publicExtensions_7 = {
	"publicExtensions",
	"publicExtensions",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_publicExtensions_tags_7,
	sizeof(asn_DEF_publicExtensions_tags_7)
		/sizeof(asn_DEF_publicExtensions_tags_7[0]), /* 1 */
	asn_DEF_publicExtensions_tags_7,	/* Same as above */
	sizeof(asn_DEF_publicExtensions_tags_7)
		/sizeof(asn_DEF_publicExtensions_tags_7[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_publicExtensions_7,
	1,	/* Single element */
	&asn_SPC_publicExtensions_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_tbs_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WaveAttestation__tbs, subject),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EntityHash,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subject"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveAttestation__tbs, subjectLocation),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_Location,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subjectLocation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveAttestation__tbs, revocations),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_revocations_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"revocations"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveAttestation__tbs, publicExtensions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_publicExtensions_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"publicExtensions"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveAttestation__tbs, body),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EXTERNAL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"body"
		},
};
static const ber_tlv_tag_t asn_DEF_tbs_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_tbs_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 0, 0, 2 }, /* subject */
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 1, -1, 1 }, /* subjectLocation */
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 4, -2, 0 }, /* body */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 1 }, /* revocations */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -1, 0 } /* publicExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_tbs_specs_2 = {
	sizeof(struct WaveAttestation__tbs),
	offsetof(struct WaveAttestation__tbs, _asn_ctx),
	asn_MAP_tbs_tag2el_2,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tbs_2 = {
	"tbs",
	"tbs",
	&asn_OP_SEQUENCE,
	asn_DEF_tbs_tags_2,
	sizeof(asn_DEF_tbs_tags_2)
		/sizeof(asn_DEF_tbs_tags_2[0]), /* 1 */
	asn_DEF_tbs_tags_2,	/* Same as above */
	sizeof(asn_DEF_tbs_tags_2)
		/sizeof(asn_DEF_tbs_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_tbs_2,
	5,	/* Elements count */
	&asn_SPC_tbs_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_WaveAttestation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WaveAttestation, tbs),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_tbs_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tbs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveAttestation, outerSignature),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EXTERNAL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"outerSignature"
		},
};
static const ber_tlv_tag_t asn_DEF_WaveAttestation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_WaveAttestation_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 1, 0, 0 }, /* outerSignature */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* tbs */
};
static asn_SEQUENCE_specifics_t asn_SPC_WaveAttestation_specs_1 = {
	sizeof(struct WaveAttestation),
	offsetof(struct WaveAttestation, _asn_ctx),
	asn_MAP_WaveAttestation_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_WaveAttestation = {
	"WaveAttestation",
	"WaveAttestation",
	&asn_OP_SEQUENCE,
	asn_DEF_WaveAttestation_tags_1,
	sizeof(asn_DEF_WaveAttestation_tags_1)
		/sizeof(asn_DEF_WaveAttestation_tags_1[0]), /* 1 */
	asn_DEF_WaveAttestation_tags_1,	/* Same as above */
	sizeof(asn_DEF_WaveAttestation_tags_1)
		/sizeof(asn_DEF_WaveAttestation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_WaveAttestation_1,
	2,	/* Elements count */
	&asn_SPC_WaveAttestation_specs_1	/* Additional specs */
};

