/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "WaveAttestationTbs.h"

static asn_TYPE_member_t asn_MBR_revocations_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RevocationOption,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_revocations_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_revocations_specs_4 = {
	sizeof(struct WaveAttestationTbs__revocations),
	offsetof(struct WaveAttestationTbs__revocations, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_revocations_4 = {
	"revocations",
	"revocations",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_revocations_tags_4,
	sizeof(asn_DEF_revocations_tags_4)
		/sizeof(asn_DEF_revocations_tags_4[0]), /* 1 */
	asn_DEF_revocations_tags_4,	/* Same as above */
	sizeof(asn_DEF_revocations_tags_4)
		/sizeof(asn_DEF_revocations_tags_4[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_revocations_4,
	1,	/* Single element */
	&asn_SPC_revocations_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_publicExtensions_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_publicExtensions_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_publicExtensions_specs_6 = {
	sizeof(struct WaveAttestationTbs__publicExtensions),
	offsetof(struct WaveAttestationTbs__publicExtensions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_publicExtensions_6 = {
	"publicExtensions",
	"publicExtensions",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_publicExtensions_tags_6,
	sizeof(asn_DEF_publicExtensions_tags_6)
		/sizeof(asn_DEF_publicExtensions_tags_6[0]), /* 1 */
	asn_DEF_publicExtensions_tags_6,	/* Same as above */
	sizeof(asn_DEF_publicExtensions_tags_6)
		/sizeof(asn_DEF_publicExtensions_tags_6[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_publicExtensions_6,
	1,	/* Single element */
	&asn_SPC_publicExtensions_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_WaveAttestationTbs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WaveAttestationTbs, subject),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EntityHash,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subject"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveAttestationTbs, subjectLocation),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_Location,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subjectLocation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveAttestationTbs, revocations),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_revocations_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"revocations"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveAttestationTbs, publicExtensions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_publicExtensions_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"publicExtensions"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveAttestationTbs, body),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EXTERNAL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"body"
		},
};
static const ber_tlv_tag_t asn_DEF_WaveAttestationTbs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_WaveAttestationTbs_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 0, 0, 2 }, /* subject */
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 1, -1, 1 }, /* subjectLocation */
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 4, -2, 0 }, /* body */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 1 }, /* revocations */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -1, 0 } /* publicExtensions */
};
asn_SEQUENCE_specifics_t asn_SPC_WaveAttestationTbs_specs_1 = {
	sizeof(struct WaveAttestationTbs),
	offsetof(struct WaveAttestationTbs, _asn_ctx),
	asn_MAP_WaveAttestationTbs_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_WaveAttestationTbs = {
	"WaveAttestationTbs",
	"WaveAttestationTbs",
	&asn_OP_SEQUENCE,
	asn_DEF_WaveAttestationTbs_tags_1,
	sizeof(asn_DEF_WaveAttestationTbs_tags_1)
		/sizeof(asn_DEF_WaveAttestationTbs_tags_1[0]), /* 1 */
	asn_DEF_WaveAttestationTbs_tags_1,	/* Same as above */
	sizeof(asn_DEF_WaveAttestationTbs_tags_1)
		/sizeof(asn_DEF_WaveAttestationTbs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_WaveAttestationTbs_1,
	5,	/* Elements count */
	&asn_SPC_WaveAttestationTbs_specs_1	/* Additional specs */
};

