/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "WaveExplicitProof.h"

static asn_TYPE_member_t asn_MBR_attestations_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AttestationReference,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_attestations_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_attestations_specs_2 = {
	sizeof(struct WaveExplicitProof__attestations),
	offsetof(struct WaveExplicitProof__attestations, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_attestations_2 = {
	"attestations",
	"attestations",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_attestations_tags_2,
	sizeof(asn_DEF_attestations_tags_2)
		/sizeof(asn_DEF_attestations_tags_2[0]), /* 1 */
	asn_DEF_attestations_tags_2,	/* Same as above */
	sizeof(asn_DEF_attestations_tags_2)
		/sizeof(asn_DEF_attestations_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_attestations_2,
	1,	/* Single element */
	&asn_SPC_attestations_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_Member_specs_5 = {
	sizeof(struct WaveExplicitProof__paths__Member),
	offsetof(struct WaveExplicitProof__paths__Member, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_5 = {
	"SEQUENCE OF",
	"SEQUENCE_OF",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_Member_tags_5,
	sizeof(asn_DEF_Member_tags_5)
		/sizeof(asn_DEF_Member_tags_5[0]), /* 1 */
	asn_DEF_Member_tags_5,	/* Same as above */
	sizeof(asn_DEF_Member_tags_5)
		/sizeof(asn_DEF_Member_tags_5[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_Member_5,
	1,	/* Single element */
	&asn_SPC_Member_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_paths_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_paths_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_paths_specs_4 = {
	sizeof(struct WaveExplicitProof__paths),
	offsetof(struct WaveExplicitProof__paths, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_paths_4 = {
	"paths",
	"paths",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_paths_tags_4,
	sizeof(asn_DEF_paths_tags_4)
		/sizeof(asn_DEF_paths_tags_4[0]), /* 1 */
	asn_DEF_paths_tags_4,	/* Same as above */
	sizeof(asn_DEF_paths_tags_4)
		/sizeof(asn_DEF_paths_tags_4[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_paths_4,
	1,	/* Single element */
	&asn_SPC_paths_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_entities_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_entities_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_entities_specs_7 = {
	sizeof(struct WaveExplicitProof__entities),
	offsetof(struct WaveExplicitProof__entities, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_entities_7 = {
	"entities",
	"entities",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_entities_tags_7,
	sizeof(asn_DEF_entities_tags_7)
		/sizeof(asn_DEF_entities_tags_7[0]), /* 1 */
	asn_DEF_entities_tags_7,	/* Same as above */
	sizeof(asn_DEF_entities_tags_7)
		/sizeof(asn_DEF_entities_tags_7[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_entities_7,
	1,	/* Single element */
	&asn_SPC_entities_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_extensions_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_extensions_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_extensions_specs_9 = {
	sizeof(struct WaveExplicitProof__extensions),
	offsetof(struct WaveExplicitProof__extensions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_extensions_9 = {
	"extensions",
	"extensions",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_extensions_tags_9,
	sizeof(asn_DEF_extensions_tags_9)
		/sizeof(asn_DEF_extensions_tags_9[0]), /* 1 */
	asn_DEF_extensions_tags_9,	/* Same as above */
	sizeof(asn_DEF_extensions_tags_9)
		/sizeof(asn_DEF_extensions_tags_9[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_extensions_9,
	1,	/* Single element */
	&asn_SPC_extensions_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_WaveExplicitProof_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WaveExplicitProof, attestations),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_attestations_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"attestations"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveExplicitProof, paths),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_paths_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"paths"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveExplicitProof, entities),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_entities_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"entities"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveExplicitProof, extensions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_extensions_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extensions"
		},
};
static const ber_tlv_tag_t asn_DEF_WaveExplicitProof_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_WaveExplicitProof_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 3 }, /* attestations */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 2 }, /* paths */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 1 }, /* entities */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 0 } /* extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_WaveExplicitProof_specs_1 = {
	sizeof(struct WaveExplicitProof),
	offsetof(struct WaveExplicitProof, _asn_ctx),
	asn_MAP_WaveExplicitProof_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_WaveExplicitProof = {
	"WaveExplicitProof",
	"WaveExplicitProof",
	&asn_OP_SEQUENCE,
	asn_DEF_WaveExplicitProof_tags_1,
	sizeof(asn_DEF_WaveExplicitProof_tags_1)
		/sizeof(asn_DEF_WaveExplicitProof_tags_1[0]), /* 1 */
	asn_DEF_WaveExplicitProof_tags_1,	/* Same as above */
	sizeof(asn_DEF_WaveExplicitProof_tags_1)
		/sizeof(asn_DEF_WaveExplicitProof_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_WaveExplicitProof_1,
	4,	/* Elements count */
	&asn_SPC_WaveExplicitProof_specs_1	/* Additional specs */
};

