/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "WaveAttestation.h"

static asn_TYPE_member_t asn_MBR_WaveAttestation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WaveAttestation, tbs),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_WaveAttestationTbs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tbs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveAttestation, outerSignature),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EXTERNAL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"outerSignature"
		},
};
static const ber_tlv_tag_t asn_DEF_WaveAttestation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_WaveAttestation_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 1, 0, 0 }, /* outerSignature */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* tbs */
};
static asn_SEQUENCE_specifics_t asn_SPC_WaveAttestation_specs_1 = {
	sizeof(struct WaveAttestation),
	offsetof(struct WaveAttestation, _asn_ctx),
	asn_MAP_WaveAttestation_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_WaveAttestation = {
	"WaveAttestation",
	"WaveAttestation",
	&asn_OP_SEQUENCE,
	asn_DEF_WaveAttestation_tags_1,
	sizeof(asn_DEF_WaveAttestation_tags_1)
		/sizeof(asn_DEF_WaveAttestation_tags_1[0]), /* 1 */
	asn_DEF_WaveAttestation_tags_1,	/* Same as above */
	sizeof(asn_DEF_WaveAttestation_tags_1)
		/sizeof(asn_DEF_WaveAttestation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_WaveAttestation_1,
	2,	/* Elements count */
	&asn_SPC_WaveAttestation_specs_1	/* Additional specs */
};

