/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "WaveEncryptedMessage.h"

static asn_TYPE_member_t asn_MBR_keys_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EXTERNAL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_keys_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_keys_specs_3 = {
	sizeof(struct WaveEncryptedMessage__keys),
	offsetof(struct WaveEncryptedMessage__keys, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_keys_3 = {
	"keys",
	"keys",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_keys_tags_3,
	sizeof(asn_DEF_keys_tags_3)
		/sizeof(asn_DEF_keys_tags_3[0]), /* 1 */
	asn_DEF_keys_tags_3,	/* Same as above */
	sizeof(asn_DEF_keys_tags_3)
		/sizeof(asn_DEF_keys_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_keys_3,
	1,	/* Single element */
	&asn_SPC_keys_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_extensions_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_extensions_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_extensions_specs_5 = {
	sizeof(struct WaveEncryptedMessage__extensions),
	offsetof(struct WaveEncryptedMessage__extensions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_extensions_5 = {
	"extensions",
	"extensions",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_extensions_tags_5,
	sizeof(asn_DEF_extensions_tags_5)
		/sizeof(asn_DEF_extensions_tags_5[0]), /* 1 */
	asn_DEF_extensions_tags_5,	/* Same as above */
	sizeof(asn_DEF_extensions_tags_5)
		/sizeof(asn_DEF_extensions_tags_5[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_extensions_5,
	1,	/* Single element */
	&asn_SPC_extensions_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_WaveEncryptedMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WaveEncryptedMessage, contents),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"contents"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveEncryptedMessage, keys),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_keys_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"keys"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveEncryptedMessage, extensions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_extensions_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extensions"
		},
};
static const ber_tlv_tag_t asn_DEF_WaveEncryptedMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_WaveEncryptedMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* contents */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 1 }, /* keys */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 0 } /* extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_WaveEncryptedMessage_specs_1 = {
	sizeof(struct WaveEncryptedMessage),
	offsetof(struct WaveEncryptedMessage, _asn_ctx),
	asn_MAP_WaveEncryptedMessage_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_WaveEncryptedMessage = {
	"WaveEncryptedMessage",
	"WaveEncryptedMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_WaveEncryptedMessage_tags_1,
	sizeof(asn_DEF_WaveEncryptedMessage_tags_1)
		/sizeof(asn_DEF_WaveEncryptedMessage_tags_1[0]), /* 1 */
	asn_DEF_WaveEncryptedMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_WaveEncryptedMessage_tags_1)
		/sizeof(asn_DEF_WaveEncryptedMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_WaveEncryptedMessage_1,
	3,	/* Elements count */
	&asn_SPC_WaveEncryptedMessage_specs_1	/* Additional specs */
};

