/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_WaveEntityTbs_H_
#define	_WaveEntityTbs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EntityPublicKey.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <UTCTime.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EntityPublicKey;
struct RevocationOption;
struct Extension;

/* WaveEntityTbs */
typedef struct WaveEntityTbs {
	EntityPublicKey_t	 verifyingKey;
	struct WaveEntityTbs__keys {
		A_SEQUENCE_OF(struct EntityPublicKey) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} keys;
	struct WaveEntityTbs__validity {
		UTCTime_t	 notBefore;
		UTCTime_t	 notAfter;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} validity;
	struct WaveEntityTbs__revocations {
		A_SEQUENCE_OF(struct RevocationOption) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} revocations;
	struct WaveEntityTbs__extensions {
		A_SEQUENCE_OF(struct Extension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WaveEntityTbs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WaveEntityTbs;
extern asn_SEQUENCE_specifics_t asn_SPC_WaveEntityTbs_specs_1;
extern asn_TYPE_member_t asn_MBR_WaveEntityTbs_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EntityPublicKey.h"
#include "RevocationOption.h"
#include "Extension.h"

#endif	/* _WaveEntityTbs_H_ */
#include <asn_internal.h>
