/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "WaveEntitySecret.h"

static asn_TYPE_member_t asn_MBR_WaveEntitySecret_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WaveEntitySecret, entity),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_WaveEntity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"entity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveEntitySecret, keyring),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EXTERNAL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"keyring"
		},
};
static const ber_tlv_tag_t asn_DEF_WaveEntitySecret_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_WaveEntitySecret_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 1, 0, 0 }, /* keyring */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* entity */
};
static asn_SEQUENCE_specifics_t asn_SPC_WaveEntitySecret_specs_1 = {
	sizeof(struct WaveEntitySecret),
	offsetof(struct WaveEntitySecret, _asn_ctx),
	asn_MAP_WaveEntitySecret_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_WaveEntitySecret = {
	"WaveEntitySecret",
	"WaveEntitySecret",
	&asn_OP_SEQUENCE,
	asn_DEF_WaveEntitySecret_tags_1,
	sizeof(asn_DEF_WaveEntitySecret_tags_1)
		/sizeof(asn_DEF_WaveEntitySecret_tags_1[0]), /* 1 */
	asn_DEF_WaveEntitySecret_tags_1,	/* Same as above */
	sizeof(asn_DEF_WaveEntitySecret_tags_1)
		/sizeof(asn_DEF_WaveEntitySecret_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_WaveEntitySecret_1,
	2,	/* Elements count */
	&asn_SPC_WaveEntitySecret_specs_1	/* Additional specs */
};

