/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_WR1BodyCiphertext_H_
#define	_WR1BodyCiphertext_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* WR1BodyCiphertext */
typedef struct WR1BodyCiphertext {
	OCTET_STRING_t	 verifierBodyCiphertext;
	OCTET_STRING_t	 proverBodyCiphertext;
	OCTET_STRING_t	 envelopeCiphertext;
	OCTET_STRING_t	 envelopeKey_ibe_bn256;
	OCTET_STRING_t	 envelopeKey_curve25519;
	OCTET_STRING_t	 envelopeKey_curve25519_attester;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WR1BodyCiphertext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WR1BodyCiphertext;

#ifdef __cplusplus
}
#endif

#endif	/* _WR1BodyCiphertext_H_ */
#include <asn_internal.h>
