/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "WR1ProverBody.h"

static asn_TYPE_member_t asn_MBR_addendums_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EXTERNAL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_addendums_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_addendums_specs_2 = {
	sizeof(struct WR1ProverBody__addendums),
	offsetof(struct WR1ProverBody__addendums, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_addendums_2 = {
	"addendums",
	"addendums",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_addendums_tags_2,
	sizeof(asn_DEF_addendums_tags_2)
		/sizeof(asn_DEF_addendums_tags_2[0]), /* 1 */
	asn_DEF_addendums_tags_2,	/* Same as above */
	sizeof(asn_DEF_addendums_tags_2)
		/sizeof(asn_DEF_addendums_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_addendums_2,
	1,	/* Single element */
	&asn_SPC_addendums_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_extensions_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_extensions_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_extensions_specs_4 = {
	sizeof(struct WR1ProverBody__extensions),
	offsetof(struct WR1ProverBody__extensions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_extensions_4 = {
	"extensions",
	"extensions",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_extensions_tags_4,
	sizeof(asn_DEF_extensions_tags_4)
		/sizeof(asn_DEF_extensions_tags_4[0]), /* 1 */
	asn_DEF_extensions_tags_4,	/* Same as above */
	sizeof(asn_DEF_extensions_tags_4)
		/sizeof(asn_DEF_extensions_tags_4[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_extensions_4,
	1,	/* Single element */
	&asn_SPC_extensions_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_WR1ProverBody_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WR1ProverBody, addendums),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_addendums_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"addendums"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WR1ProverBody, extensions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_extensions_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extensions"
		},
};
static const ber_tlv_tag_t asn_DEF_WR1ProverBody_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_WR1ProverBody_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* addendums */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 0 } /* extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_WR1ProverBody_specs_1 = {
	sizeof(struct WR1ProverBody),
	offsetof(struct WR1ProverBody, _asn_ctx),
	asn_MAP_WR1ProverBody_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_WR1ProverBody = {
	"WR1ProverBody",
	"WR1ProverBody",
	&asn_OP_SEQUENCE,
	asn_DEF_WR1ProverBody_tags_1,
	sizeof(asn_DEF_WR1ProverBody_tags_1)
		/sizeof(asn_DEF_WR1ProverBody_tags_1[0]), /* 1 */
	asn_DEF_WR1ProverBody_tags_1,	/* Same as above */
	sizeof(asn_DEF_WR1ProverBody_tags_1)
		/sizeof(asn_DEF_WR1ProverBody_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_WR1ProverBody_1,
	2,	/* Elements count */
	&asn_SPC_WR1ProverBody_specs_1	/* Additional specs */
};

