/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_WR1ProverBody_H_
#define	_WR1ProverBody_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EXTERNAL;
struct Extension;

/* WR1ProverBody */
typedef struct WR1ProverBody {
	struct WR1ProverBody__addendums {
		A_SEQUENCE_OF(struct EXTERNAL) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} addendums;
	struct WR1ProverBody__extensions {
		A_SEQUENCE_OF(struct Extension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WR1ProverBody_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WR1ProverBody;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EXTERNAL.h"
#include "Extension.h"

#endif	/* _WR1ProverBody_H_ */
#include <asn_internal.h>
