/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "AttestationBody.h"

static asn_TYPE_member_t asn_MBR_proverPolicyAddendums_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EXTERNAL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_proverPolicyAddendums_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_proverPolicyAddendums_specs_3 = {
	sizeof(struct AttestationBody__proverPolicyAddendums),
	offsetof(struct AttestationBody__proverPolicyAddendums, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_proverPolicyAddendums_3 = {
	"proverPolicyAddendums",
	"proverPolicyAddendums",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_proverPolicyAddendums_tags_3,
	sizeof(asn_DEF_proverPolicyAddendums_tags_3)
		/sizeof(asn_DEF_proverPolicyAddendums_tags_3[0]), /* 1 */
	asn_DEF_proverPolicyAddendums_tags_3,	/* Same as above */
	sizeof(asn_DEF_proverPolicyAddendums_tags_3)
		/sizeof(asn_DEF_proverPolicyAddendums_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_proverPolicyAddendums_3,
	1,	/* Single element */
	&asn_SPC_proverPolicyAddendums_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_proverExtensions_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_proverExtensions_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_proverExtensions_specs_5 = {
	sizeof(struct AttestationBody__proverExtensions),
	offsetof(struct AttestationBody__proverExtensions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_proverExtensions_5 = {
	"proverExtensions",
	"proverExtensions",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_proverExtensions_tags_5,
	sizeof(asn_DEF_proverExtensions_tags_5)
		/sizeof(asn_DEF_proverExtensions_tags_5[0]), /* 1 */
	asn_DEF_proverExtensions_tags_5,	/* Same as above */
	sizeof(asn_DEF_proverExtensions_tags_5)
		/sizeof(asn_DEF_proverExtensions_tags_5[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_proverExtensions_5,
	1,	/* Single element */
	&asn_SPC_proverExtensions_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_AttestationBody_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationBody, verifierBody),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AttestationVerifierBody,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"verifierBody"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationBody, proverPolicyAddendums),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_proverPolicyAddendums_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"proverPolicyAddendums"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationBody, proverExtensions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_proverExtensions_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"proverExtensions"
		},
};
static const ber_tlv_tag_t asn_DEF_AttestationBody_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AttestationBody_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 2 }, /* verifierBody */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 1 }, /* proverPolicyAddendums */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 0 } /* proverExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_AttestationBody_specs_1 = {
	sizeof(struct AttestationBody),
	offsetof(struct AttestationBody, _asn_ctx),
	asn_MAP_AttestationBody_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AttestationBody = {
	"AttestationBody",
	"AttestationBody",
	&asn_OP_SEQUENCE,
	asn_DEF_AttestationBody_tags_1,
	sizeof(asn_DEF_AttestationBody_tags_1)
		/sizeof(asn_DEF_AttestationBody_tags_1[0]), /* 1 */
	asn_DEF_AttestationBody_tags_1,	/* Same as above */
	sizeof(asn_DEF_AttestationBody_tags_1)
		/sizeof(asn_DEF_AttestationBody_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AttestationBody_1,
	3,	/* Elements count */
	&asn_SPC_AttestationBody_specs_1	/* Additional specs */
};

