/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "AttestationVerifierBody.h"

static asn_TYPE_member_t asn_MBR_validity_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationVerifierBody__validity, notBefore),
		(ASN_TAG_CLASS_UNIVERSAL | (23 << 2)),
		0,
		&asn_DEF_UTCTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notBefore"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationVerifierBody__validity, notAfter),
		(ASN_TAG_CLASS_UNIVERSAL | (23 << 2)),
		0,
		&asn_DEF_UTCTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notAfter"
		},
};
static const ber_tlv_tag_t asn_DEF_validity_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_validity_tag2el_4[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (23 << 2)), 0, 0, 1 }, /* notBefore */
    { (ASN_TAG_CLASS_UNIVERSAL | (23 << 2)), 1, -1, 0 } /* notAfter */
};
static asn_SEQUENCE_specifics_t asn_SPC_validity_specs_4 = {
	sizeof(struct AttestationVerifierBody__validity),
	offsetof(struct AttestationVerifierBody__validity, _asn_ctx),
	asn_MAP_validity_tag2el_4,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_validity_4 = {
	"validity",
	"validity",
	&asn_OP_SEQUENCE,
	asn_DEF_validity_tags_4,
	sizeof(asn_DEF_validity_tags_4)
		/sizeof(asn_DEF_validity_tags_4[0]), /* 1 */
	asn_DEF_validity_tags_4,	/* Same as above */
	sizeof(asn_DEF_validity_tags_4)
		/sizeof(asn_DEF_validity_tags_4[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_validity_4,
	2,	/* Elements count */
	&asn_SPC_validity_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_extensions_8[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_extensions_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_extensions_specs_8 = {
	sizeof(struct AttestationVerifierBody__extensions),
	offsetof(struct AttestationVerifierBody__extensions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_extensions_8 = {
	"extensions",
	"extensions",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_extensions_tags_8,
	sizeof(asn_DEF_extensions_tags_8)
		/sizeof(asn_DEF_extensions_tags_8[0]), /* 1 */
	asn_DEF_extensions_tags_8,	/* Same as above */
	sizeof(asn_DEF_extensions_tags_8)
		/sizeof(asn_DEF_extensions_tags_8[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_extensions_8,
	1,	/* Single element */
	&asn_SPC_extensions_specs_8	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_AttestationVerifierBody_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationVerifierBody, attester),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EntityHash,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"attester"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationVerifierBody, attesterLocation),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_Location,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"attesterLocation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationVerifierBody, validity),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_validity_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"validity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationVerifierBody, policy),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EXTERNAL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"policy"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationVerifierBody, extensions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_extensions_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extensions"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationVerifierBody, outerSignatureBinding),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EXTERNAL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"outerSignatureBinding"
		},
};
static const ber_tlv_tag_t asn_DEF_AttestationVerifierBody_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AttestationVerifierBody_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 0, 0, 3 }, /* attester */
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 1, -1, 2 }, /* attesterLocation */
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 3, -2, 1 }, /* policy */
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 5, -3, 0 }, /* outerSignatureBinding */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 1 }, /* validity */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -1, 0 } /* extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_AttestationVerifierBody_specs_1 = {
	sizeof(struct AttestationVerifierBody),
	offsetof(struct AttestationVerifierBody, _asn_ctx),
	asn_MAP_AttestationVerifierBody_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AttestationVerifierBody = {
	"AttestationVerifierBody",
	"AttestationVerifierBody",
	&asn_OP_SEQUENCE,
	asn_DEF_AttestationVerifierBody_tags_1,
	sizeof(asn_DEF_AttestationVerifierBody_tags_1)
		/sizeof(asn_DEF_AttestationVerifierBody_tags_1[0]), /* 1 */
	asn_DEF_AttestationVerifierBody_tags_1,	/* Same as above */
	sizeof(asn_DEF_AttestationVerifierBody_tags_1)
		/sizeof(asn_DEF_AttestationVerifierBody_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AttestationVerifierBody_1,
	6,	/* Elements count */
	&asn_SPC_AttestationVerifierBody_specs_1	/* Additional specs */
};

