/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "AttestationReference.h"

static asn_TYPE_member_t asn_MBR_location_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_Location,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_location_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_location_specs_4 = {
	sizeof(struct AttestationReference__location),
	offsetof(struct AttestationReference__location, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_location_4 = {
	"location",
	"location",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_location_tags_4,
	sizeof(asn_DEF_location_tags_4)
		/sizeof(asn_DEF_location_tags_4[0]), /* 2 */
	asn_DEF_location_tags_4,	/* Same as above */
	sizeof(asn_DEF_location_tags_4)
		/sizeof(asn_DEF_location_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_location_4,
	1,	/* Single element */
	&asn_SPC_location_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_keys_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_AttestationVerifierKey,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_keys_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_keys_specs_6 = {
	sizeof(struct AttestationReference__keys),
	offsetof(struct AttestationReference__keys, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_keys_6 = {
	"keys",
	"keys",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_keys_tags_6,
	sizeof(asn_DEF_keys_tags_6)
		/sizeof(asn_DEF_keys_tags_6[0]), /* 2 */
	asn_DEF_keys_tags_6,	/* Same as above */
	sizeof(asn_DEF_keys_tags_6)
		/sizeof(asn_DEF_keys_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_keys_6,
	1,	/* Single element */
	&asn_SPC_keys_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_revocationChecks_8[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_RevocationCheck,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_revocationChecks_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_revocationChecks_specs_8 = {
	sizeof(struct AttestationReference__revocationChecks),
	offsetof(struct AttestationReference__revocationChecks, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_revocationChecks_8 = {
	"revocationChecks",
	"revocationChecks",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_revocationChecks_tags_8,
	sizeof(asn_DEF_revocationChecks_tags_8)
		/sizeof(asn_DEF_revocationChecks_tags_8[0]), /* 2 */
	asn_DEF_revocationChecks_tags_8,	/* Same as above */
	sizeof(asn_DEF_revocationChecks_tags_8)
		/sizeof(asn_DEF_revocationChecks_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_revocationChecks_8,
	1,	/* Single element */
	&asn_SPC_revocationChecks_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_extensions_10[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_extensions_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_extensions_specs_10 = {
	sizeof(struct AttestationReference__extensions),
	offsetof(struct AttestationReference__extensions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_extensions_10 = {
	"extensions",
	"extensions",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_extensions_tags_10,
	sizeof(asn_DEF_extensions_tags_10)
		/sizeof(asn_DEF_extensions_tags_10[0]), /* 2 */
	asn_DEF_extensions_tags_10,	/* Same as above */
	sizeof(asn_DEF_extensions_tags_10)
		/sizeof(asn_DEF_extensions_tags_10[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_extensions_10,
	1,	/* Single element */
	&asn_SPC_extensions_specs_10	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_AttestationReference_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationReference, hash),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_AttestationHash,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hash"
		},
	{ ATF_POINTER, 1, offsetof(struct AttestationReference, content),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"content"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationReference, location),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_location_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"location"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationReference, keys),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_keys_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"keys"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationReference, revocationChecks),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_revocationChecks_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"revocationChecks"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttestationReference, extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_extensions_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extensions"
		},
};
static const int asn_MAP_AttestationReference_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_AttestationReference_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AttestationReference_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 0, 0, 0 }, /* hash */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* content */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* location */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 }, /* keys */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 4, 0, 0 }, /* revocationChecks */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 5, 0, 0 } /* extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_AttestationReference_specs_1 = {
	sizeof(struct AttestationReference),
	offsetof(struct AttestationReference, _asn_ctx),
	asn_MAP_AttestationReference_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_AttestationReference_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AttestationReference = {
	"AttestationReference",
	"AttestationReference",
	&asn_OP_SEQUENCE,
	asn_DEF_AttestationReference_tags_1,
	sizeof(asn_DEF_AttestationReference_tags_1)
		/sizeof(asn_DEF_AttestationReference_tags_1[0]), /* 1 */
	asn_DEF_AttestationReference_tags_1,	/* Same as above */
	sizeof(asn_DEF_AttestationReference_tags_1)
		/sizeof(asn_DEF_AttestationReference_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AttestationReference_1,
	6,	/* Elements count */
	&asn_SPC_AttestationReference_specs_1	/* Additional specs */
};

