/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "CommitmentRevocationOption.h"

static asn_TYPE_member_t asn_MBR_CommitmentRevocationOption_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CommitmentRevocationOption, hash),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_Hash,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hash"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CommitmentRevocationOption, location),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_Location,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"location"
		},
};
static const ber_tlv_tag_t asn_DEF_CommitmentRevocationOption_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CommitmentRevocationOption_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 0, 0, 1 }, /* hash */
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 1, -1, 0 } /* location */
};
static asn_SEQUENCE_specifics_t asn_SPC_CommitmentRevocationOption_specs_1 = {
	sizeof(struct CommitmentRevocationOption),
	offsetof(struct CommitmentRevocationOption, _asn_ctx),
	asn_MAP_CommitmentRevocationOption_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CommitmentRevocationOption = {
	"CommitmentRevocationOption",
	"CommitmentRevocationOption",
	&asn_OP_SEQUENCE,
	asn_DEF_CommitmentRevocationOption_tags_1,
	sizeof(asn_DEF_CommitmentRevocationOption_tags_1)
		/sizeof(asn_DEF_CommitmentRevocationOption_tags_1[0]), /* 1 */
	asn_DEF_CommitmentRevocationOption_tags_1,	/* Same as above */
	sizeof(asn_DEF_CommitmentRevocationOption_tags_1)
		/sizeof(asn_DEF_CommitmentRevocationOption_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CommitmentRevocationOption_1,
	2,	/* Elements count */
	&asn_SPC_CommitmentRevocationOption_specs_1	/* Additional specs */
};

