/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "EntityKeyring.h"

static asn_TYPE_member_t asn_MBR_keys_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EntityKeyringEntry,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_keys_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_keys_specs_2 = {
	sizeof(struct EntityKeyring__keys),
	offsetof(struct EntityKeyring__keys, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_keys_2 = {
	"keys",
	"keys",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_keys_tags_2,
	sizeof(asn_DEF_keys_tags_2)
		/sizeof(asn_DEF_keys_tags_2[0]), /* 1 */
	asn_DEF_keys_tags_2,	/* Same as above */
	sizeof(asn_DEF_keys_tags_2)
		/sizeof(asn_DEF_keys_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_keys_2,
	1,	/* Single element */
	&asn_SPC_keys_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_EntityKeyring_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EntityKeyring, keys),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_keys_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"keys"
		},
};
static const ber_tlv_tag_t asn_DEF_EntityKeyring_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EntityKeyring_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* keys */
};
static asn_SEQUENCE_specifics_t asn_SPC_EntityKeyring_specs_1 = {
	sizeof(struct EntityKeyring),
	offsetof(struct EntityKeyring, _asn_ctx),
	asn_MAP_EntityKeyring_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EntityKeyring = {
	"EntityKeyring",
	"EntityKeyring",
	&asn_OP_SEQUENCE,
	asn_DEF_EntityKeyring_tags_1,
	sizeof(asn_DEF_EntityKeyring_tags_1)
		/sizeof(asn_DEF_EntityKeyring_tags_1[0]), /* 1 */
	asn_DEF_EntityKeyring_tags_1,	/* Same as above */
	sizeof(asn_DEF_EntityKeyring_tags_1)
		/sizeof(asn_DEF_EntityKeyring_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EntityKeyring_1,
	1,	/* Elements count */
	&asn_SPC_EntityKeyring_specs_1	/* Additional specs */
};

