/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_WaveWireObject;
extern struct asn_TYPE_descriptor_s asn_DEF_WaveAttestation;
extern struct asn_TYPE_descriptor_s asn_DEF_WaveEncryptedMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_AttestationBody;
extern struct asn_TYPE_descriptor_s asn_DEF_WaveEntitySecret;
extern struct asn_TYPE_descriptor_s asn_DEF_EntityKeyring;
extern struct asn_TYPE_descriptor_s asn_DEF_BLS12381OAQUEKeyringBundle;
extern struct asn_TYPE_descriptor_s asn_DEF_WaveExplicitProof;
extern struct asn_TYPE_descriptor_s asn_DEF_RTreePolicy;
extern struct asn_TYPE_descriptor_s asn_DEF_HashSha3_256;
extern struct asn_TYPE_descriptor_s asn_DEF_HashSha_256;
extern struct asn_TYPE_descriptor_s asn_DEF_HashKeccak_256;
extern struct asn_TYPE_descriptor_s asn_DEF_LocationURL;
extern struct asn_TYPE_descriptor_s asn_DEF_LocationEthereum;
extern struct asn_TYPE_descriptor_s asn_DEF_PSKBodyCiphertext;
extern struct asn_TYPE_descriptor_s asn_DEF_WaveNameDeclaration;
extern struct asn_TYPE_descriptor_s asn_DEF_NameDeclarationBody;
extern struct asn_TYPE_descriptor_s asn_DEF_NameDeclarationKeyNone;
extern struct asn_TYPE_descriptor_s asn_DEF_NameDeclarationKeyWR1;
extern struct asn_TYPE_descriptor_s asn_DEF_NameDeclarationWR1Envelope;
extern struct asn_TYPE_descriptor_s asn_DEF_WR1BodyCiphertext;
extern struct asn_TYPE_descriptor_s asn_DEF_WR1Envelope;
extern struct asn_TYPE_descriptor_s asn_DEF_WR1ProverBody;
extern struct asn_TYPE_descriptor_s asn_DEF_WR1VerifierBody;
extern struct asn_TYPE_descriptor_s asn_DEF_Ed25519OuterSignature;
extern struct asn_TYPE_descriptor_s asn_DEF_Signature;
extern struct asn_TYPE_descriptor_s asn_DEF_SignedOuterKey;
extern struct asn_TYPE_descriptor_s asn_DEF_TrustLevel;
extern struct asn_TYPE_descriptor_s asn_DEF_CommitmentRevocationOption;
extern struct asn_TYPE_descriptor_s asn_DEF_AVKeyAES128_GCM;
extern struct asn_TYPE_descriptor_s asn_DEF_Private_Ed25519;
extern struct asn_TYPE_descriptor_s asn_DEF_Private_Curve25519;
extern struct asn_TYPE_descriptor_s asn_DEF_Private_BLS12381_IBE;
extern struct asn_TYPE_descriptor_s asn_DEF_Master_BLS12381_OAQUE;
extern struct asn_TYPE_descriptor_s asn_DEF_Master_BLS12381_IBE;
extern struct asn_TYPE_descriptor_s asn_DEF_Public_Ed25519;
extern struct asn_TYPE_descriptor_s asn_DEF_Public_Curve25519;
extern struct asn_TYPE_descriptor_s asn_DEF_Public_OAQUE;
extern struct asn_TYPE_descriptor_s asn_DEF_Public_BLS12381_IBE;
extern struct asn_TYPE_descriptor_s asn_DEF_KeyringAESCiphertext;
extern struct asn_TYPE_descriptor_s asn_DEF_MessageKeyCurve25519ECDH;
extern struct asn_TYPE_descriptor_s asn_DEF_MessageKeyWR1;
extern struct asn_TYPE_descriptor_s asn_DEF_MessageKeyWR1Envelope;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module WAVE-Schema in objects-lite.asn */
	&asn_DEF_WaveWireObject,	
	&asn_DEF_WaveAttestation,	
	&asn_DEF_WaveEncryptedMessage,	
	&asn_DEF_AttestationBody,	
	&asn_DEF_WaveEntitySecret,	
	&asn_DEF_EntityKeyring,	
	&asn_DEF_BLS12381OAQUEKeyringBundle,	
	&asn_DEF_WaveExplicitProof,	
	&asn_DEF_RTreePolicy,	
	&asn_DEF_HashSha3_256,	
	&asn_DEF_HashSha_256,	
	&asn_DEF_HashKeccak_256,	
	&asn_DEF_LocationURL,	
	&asn_DEF_LocationEthereum,	
	&asn_DEF_PSKBodyCiphertext,	
	&asn_DEF_WaveNameDeclaration,	
	&asn_DEF_NameDeclarationBody,	
	&asn_DEF_NameDeclarationKeyNone,	
	&asn_DEF_NameDeclarationKeyWR1,	
	&asn_DEF_NameDeclarationWR1Envelope,	
	&asn_DEF_WR1BodyCiphertext,	
	&asn_DEF_WR1Envelope,	
	&asn_DEF_WR1ProverBody,	
	&asn_DEF_WR1VerifierBody,	
	&asn_DEF_Ed25519OuterSignature,	
	&asn_DEF_Signature,	
	&asn_DEF_SignedOuterKey,	
	&asn_DEF_TrustLevel,	
	&asn_DEF_CommitmentRevocationOption,	
	&asn_DEF_AVKeyAES128_GCM,	
	&asn_DEF_Private_Ed25519,	
	&asn_DEF_Private_Curve25519,	
	&asn_DEF_Private_BLS12381_IBE,	
	&asn_DEF_Master_BLS12381_OAQUE,	
	&asn_DEF_Master_BLS12381_IBE,	
	&asn_DEF_Public_Ed25519,	
	&asn_DEF_Public_Curve25519,	
	&asn_DEF_Public_OAQUE,	
	&asn_DEF_Public_BLS12381_IBE,	
	&asn_DEF_KeyringAESCiphertext,	
	&asn_DEF_MessageKeyCurve25519ECDH,	
	&asn_DEF_MessageKeyWR1,	
	&asn_DEF_MessageKeyWR1Envelope,	
	0
};

