/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "PSKBodyCiphertext.h"

static asn_TYPE_member_t asn_MBR_PSKBodyCiphertext_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PSKBodyCiphertext, attestationBodyCiphertext),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"attestationBodyCiphertext"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PSKBodyCiphertext, encryptedUnder),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EntityPublicKey,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"encryptedUnder"
		},
};
static const ber_tlv_tag_t asn_DEF_PSKBodyCiphertext_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PSKBodyCiphertext_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* attestationBodyCiphertext */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 } /* encryptedUnder */
};
static asn_SEQUENCE_specifics_t asn_SPC_PSKBodyCiphertext_specs_1 = {
	sizeof(struct PSKBodyCiphertext),
	offsetof(struct PSKBodyCiphertext, _asn_ctx),
	asn_MAP_PSKBodyCiphertext_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PSKBodyCiphertext = {
	"PSKBodyCiphertext",
	"PSKBodyCiphertext",
	&asn_OP_SEQUENCE,
	asn_DEF_PSKBodyCiphertext_tags_1,
	sizeof(asn_DEF_PSKBodyCiphertext_tags_1)
		/sizeof(asn_DEF_PSKBodyCiphertext_tags_1[0]), /* 1 */
	asn_DEF_PSKBodyCiphertext_tags_1,	/* Same as above */
	sizeof(asn_DEF_PSKBodyCiphertext_tags_1)
		/sizeof(asn_DEF_PSKBodyCiphertext_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PSKBodyCiphertext_1,
	2,	/* Elements count */
	&asn_SPC_PSKBodyCiphertext_specs_1	/* Additional specs */
};

