/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "WaveNameDeclaration.h"

static asn_TYPE_member_t asn_MBR_revocations_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RevocationOption,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_revocations_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_revocations_specs_5 = {
	sizeof(struct WaveNameDeclaration__tbs__revocations),
	offsetof(struct WaveNameDeclaration__tbs__revocations, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_revocations_5 = {
	"revocations",
	"revocations",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_revocations_tags_5,
	sizeof(asn_DEF_revocations_tags_5)
		/sizeof(asn_DEF_revocations_tags_5[0]), /* 1 */
	asn_DEF_revocations_tags_5,	/* Same as above */
	sizeof(asn_DEF_revocations_tags_5)
		/sizeof(asn_DEF_revocations_tags_5[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_revocations_5,
	1,	/* Single element */
	&asn_SPC_revocations_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_publicExtensions_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_publicExtensions_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_publicExtensions_specs_7 = {
	sizeof(struct WaveNameDeclaration__tbs__publicExtensions),
	offsetof(struct WaveNameDeclaration__tbs__publicExtensions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_publicExtensions_7 = {
	"publicExtensions",
	"publicExtensions",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_publicExtensions_tags_7,
	sizeof(asn_DEF_publicExtensions_tags_7)
		/sizeof(asn_DEF_publicExtensions_tags_7[0]), /* 1 */
	asn_DEF_publicExtensions_tags_7,	/* Same as above */
	sizeof(asn_DEF_publicExtensions_tags_7)
		/sizeof(asn_DEF_publicExtensions_tags_7[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_publicExtensions_7,
	1,	/* Single element */
	&asn_SPC_publicExtensions_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_keys_10[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_NameDeclarationKey,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_keys_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_keys_specs_10 = {
	sizeof(struct WaveNameDeclaration__tbs__keys),
	offsetof(struct WaveNameDeclaration__tbs__keys, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_keys_10 = {
	"keys",
	"keys",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_keys_tags_10,
	sizeof(asn_DEF_keys_tags_10)
		/sizeof(asn_DEF_keys_tags_10[0]), /* 1 */
	asn_DEF_keys_tags_10,	/* Same as above */
	sizeof(asn_DEF_keys_tags_10)
		/sizeof(asn_DEF_keys_tags_10[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_keys_10,
	1,	/* Single element */
	&asn_SPC_keys_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_tbs_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WaveNameDeclaration__tbs, attester),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_EntityHash,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"attester"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveNameDeclaration__tbs, attesterLocation),
		(ASN_TAG_CLASS_UNIVERSAL | (8 << 2)),
		0,
		&asn_DEF_Location,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"attesterLocation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveNameDeclaration__tbs, revocations),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_revocations_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"revocations"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveNameDeclaration__tbs, publicExtensions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_publicExtensions_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"publicExtensions"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveNameDeclaration__tbs, body),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"body"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveNameDeclaration__tbs, keys),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_keys_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"keys"
		},
};
static const ber_tlv_tag_t asn_DEF_tbs_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_tbs_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 4, 0, 0 }, /* body */
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 0, 0, 1 }, /* attester */
    { (ASN_TAG_CLASS_UNIVERSAL | (8 << 2)), 1, -1, 0 }, /* attesterLocation */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 2 }, /* revocations */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -1, 1 }, /* publicExtensions */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -2, 0 } /* keys */
};
static asn_SEQUENCE_specifics_t asn_SPC_tbs_specs_2 = {
	sizeof(struct WaveNameDeclaration__tbs),
	offsetof(struct WaveNameDeclaration__tbs, _asn_ctx),
	asn_MAP_tbs_tag2el_2,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tbs_2 = {
	"tbs",
	"tbs",
	&asn_OP_SEQUENCE,
	asn_DEF_tbs_tags_2,
	sizeof(asn_DEF_tbs_tags_2)
		/sizeof(asn_DEF_tbs_tags_2[0]), /* 1 */
	asn_DEF_tbs_tags_2,	/* Same as above */
	sizeof(asn_DEF_tbs_tags_2)
		/sizeof(asn_DEF_tbs_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_tbs_2,
	6,	/* Elements count */
	&asn_SPC_tbs_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_WaveNameDeclaration_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WaveNameDeclaration, tbs),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_tbs_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tbs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveNameDeclaration, signature),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signature"
		},
};
static const ber_tlv_tag_t asn_DEF_WaveNameDeclaration_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_WaveNameDeclaration_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* signature */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* tbs */
};
static asn_SEQUENCE_specifics_t asn_SPC_WaveNameDeclaration_specs_1 = {
	sizeof(struct WaveNameDeclaration),
	offsetof(struct WaveNameDeclaration, _asn_ctx),
	asn_MAP_WaveNameDeclaration_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_WaveNameDeclaration = {
	"WaveNameDeclaration",
	"WaveNameDeclaration",
	&asn_OP_SEQUENCE,
	asn_DEF_WaveNameDeclaration_tags_1,
	sizeof(asn_DEF_WaveNameDeclaration_tags_1)
		/sizeof(asn_DEF_WaveNameDeclaration_tags_1[0]), /* 1 */
	asn_DEF_WaveNameDeclaration_tags_1,	/* Same as above */
	sizeof(asn_DEF_WaveNameDeclaration_tags_1)
		/sizeof(asn_DEF_WaveNameDeclaration_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_WaveNameDeclaration_1,
	2,	/* Elements count */
	&asn_SPC_WaveNameDeclaration_specs_1	/* Additional specs */
};

