/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "WaveEntity.h"

asn_TYPE_member_t asn_MBR_WaveEntity_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WaveEntity, tbs),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_WaveEntityTbs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tbs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveEntity, signature),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signature"
		},
};
static const ber_tlv_tag_t asn_DEF_WaveEntity_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_WaveEntity_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* signature */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* tbs */
};
asn_SEQUENCE_specifics_t asn_SPC_WaveEntity_specs_1 = {
	sizeof(struct WaveEntity),
	offsetof(struct WaveEntity, _asn_ctx),
	asn_MAP_WaveEntity_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_WaveEntity = {
	"WaveEntity",
	"WaveEntity",
	&asn_OP_SEQUENCE,
	asn_DEF_WaveEntity_tags_1,
	sizeof(asn_DEF_WaveEntity_tags_1)
		/sizeof(asn_DEF_WaveEntity_tags_1[0]), /* 1 */
	asn_DEF_WaveEntity_tags_1,	/* Same as above */
	sizeof(asn_DEF_WaveEntity_tags_1)
		/sizeof(asn_DEF_WaveEntity_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_WaveEntity_1,
	2,	/* Elements count */
	&asn_SPC_WaveEntity_specs_1	/* Additional specs */
};

