/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#include "WaveEntityTbs.h"

static asn_TYPE_member_t asn_MBR_keys_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EntityPublicKey,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_keys_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_keys_specs_3 = {
	sizeof(struct WaveEntityTbs__keys),
	offsetof(struct WaveEntityTbs__keys, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_keys_3 = {
	"keys",
	"keys",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_keys_tags_3,
	sizeof(asn_DEF_keys_tags_3)
		/sizeof(asn_DEF_keys_tags_3[0]), /* 1 */
	asn_DEF_keys_tags_3,	/* Same as above */
	sizeof(asn_DEF_keys_tags_3)
		/sizeof(asn_DEF_keys_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_keys_3,
	1,	/* Single element */
	&asn_SPC_keys_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_validity_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WaveEntityTbs__validity, notBefore),
		(ASN_TAG_CLASS_UNIVERSAL | (23 << 2)),
		0,
		&asn_DEF_UTCTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notBefore"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveEntityTbs__validity, notAfter),
		(ASN_TAG_CLASS_UNIVERSAL | (23 << 2)),
		0,
		&asn_DEF_UTCTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notAfter"
		},
};
static const ber_tlv_tag_t asn_DEF_validity_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_validity_tag2el_5[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (23 << 2)), 0, 0, 1 }, /* notBefore */
    { (ASN_TAG_CLASS_UNIVERSAL | (23 << 2)), 1, -1, 0 } /* notAfter */
};
static asn_SEQUENCE_specifics_t asn_SPC_validity_specs_5 = {
	sizeof(struct WaveEntityTbs__validity),
	offsetof(struct WaveEntityTbs__validity, _asn_ctx),
	asn_MAP_validity_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_validity_5 = {
	"validity",
	"validity",
	&asn_OP_SEQUENCE,
	asn_DEF_validity_tags_5,
	sizeof(asn_DEF_validity_tags_5)
		/sizeof(asn_DEF_validity_tags_5[0]), /* 1 */
	asn_DEF_validity_tags_5,	/* Same as above */
	sizeof(asn_DEF_validity_tags_5)
		/sizeof(asn_DEF_validity_tags_5[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_validity_5,
	2,	/* Elements count */
	&asn_SPC_validity_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_revocations_8[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RevocationOption,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_revocations_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_revocations_specs_8 = {
	sizeof(struct WaveEntityTbs__revocations),
	offsetof(struct WaveEntityTbs__revocations, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_revocations_8 = {
	"revocations",
	"revocations",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_revocations_tags_8,
	sizeof(asn_DEF_revocations_tags_8)
		/sizeof(asn_DEF_revocations_tags_8[0]), /* 1 */
	asn_DEF_revocations_tags_8,	/* Same as above */
	sizeof(asn_DEF_revocations_tags_8)
		/sizeof(asn_DEF_revocations_tags_8[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_revocations_8,
	1,	/* Single element */
	&asn_SPC_revocations_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_extensions_10[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_extensions_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_extensions_specs_10 = {
	sizeof(struct WaveEntityTbs__extensions),
	offsetof(struct WaveEntityTbs__extensions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_extensions_10 = {
	"extensions",
	"extensions",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_extensions_tags_10,
	sizeof(asn_DEF_extensions_tags_10)
		/sizeof(asn_DEF_extensions_tags_10[0]), /* 1 */
	asn_DEF_extensions_tags_10,	/* Same as above */
	sizeof(asn_DEF_extensions_tags_10)
		/sizeof(asn_DEF_extensions_tags_10[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_extensions_10,
	1,	/* Single element */
	&asn_SPC_extensions_specs_10	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_WaveEntityTbs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WaveEntityTbs, verifyingKey),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EntityPublicKey,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"verifyingKey"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveEntityTbs, keys),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_keys_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"keys"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveEntityTbs, validity),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_validity_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"validity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveEntityTbs, revocations),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_revocations_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"revocations"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WaveEntityTbs, extensions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_extensions_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extensions"
		},
};
static const ber_tlv_tag_t asn_DEF_WaveEntityTbs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_WaveEntityTbs_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 4 }, /* verifyingKey */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 3 }, /* keys */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 2 }, /* validity */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 1 }, /* revocations */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -4, 0 } /* extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_WaveEntityTbs_specs_1 = {
	sizeof(struct WaveEntityTbs),
	offsetof(struct WaveEntityTbs, _asn_ctx),
	asn_MAP_WaveEntityTbs_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_WaveEntityTbs = {
	"WaveEntityTbs",
	"WaveEntityTbs",
	&asn_OP_SEQUENCE,
	asn_DEF_WaveEntityTbs_tags_1,
	sizeof(asn_DEF_WaveEntityTbs_tags_1)
		/sizeof(asn_DEF_WaveEntityTbs_tags_1[0]), /* 1 */
	asn_DEF_WaveEntityTbs_tags_1,	/* Same as above */
	sizeof(asn_DEF_WaveEntityTbs_tags_1)
		/sizeof(asn_DEF_WaveEntityTbs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_WaveEntityTbs_1,
	5,	/* Elements count */
	&asn_SPC_WaveEntityTbs_specs_1	/* Additional specs */
};

