/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AttestationVerifierBody_H_
#define	_AttestationVerifierBody_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EntityHash.h"
#include "Location.h"
#include "EXTERNAL.h"
#include <UTCTime.h>
#include <constr_SEQUENCE.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Extension;

/* AttestationVerifierBody */
typedef struct AttestationVerifierBody {
	EntityHash_t	 attester;
	Location_t	 attesterLocation;
	struct AttestationVerifierBody__validity {
		UTCTime_t	 notBefore;
		UTCTime_t	 notAfter;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} validity;
	EXTERNAL_t	 policy;
	struct AttestationVerifierBody__extensions {
		A_SEQUENCE_OF(struct Extension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensions;
	EXTERNAL_t	 outerSignatureBinding;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttestationVerifierBody_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttestationVerifierBody;
extern asn_SEQUENCE_specifics_t asn_SPC_AttestationVerifierBody_specs_1;
extern asn_TYPE_member_t asn_MBR_AttestationVerifierBody_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Extension.h"

#endif	/* _AttestationVerifierBody_H_ */
#include <asn_internal.h>
