/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AttestationVerifierKey_H_
#define	_AttestationVerifierKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EXTERNAL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AttestationVerifierKey */
typedef EXTERNAL_t	 AttestationVerifierKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttestationVerifierKey;
asn_struct_free_f AttestationVerifierKey_free;
asn_struct_print_f AttestationVerifierKey_print;
asn_constr_check_f AttestationVerifierKey_constraint;
ber_type_decoder_f AttestationVerifierKey_decode_ber;
der_type_encoder_f AttestationVerifierKey_encode_der;
xer_type_decoder_f AttestationVerifierKey_decode_xer;
xer_type_encoder_f AttestationVerifierKey_encode_xer;
oer_type_decoder_f AttestationVerifierKey_decode_oer;
oer_type_encoder_f AttestationVerifierKey_encode_oer;
per_type_decoder_f AttestationVerifierKey_decode_uper;
per_type_encoder_f AttestationVerifierKey_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AttestationVerifierKey_H_ */
#include <asn_internal.h>
