/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AttestationReference_H_
#define	_AttestationReference_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttestationHash.h"
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Location;
struct AttestationVerifierKey;
struct RevocationCheck;
struct Extension;

/* AttestationReference */
typedef struct AttestationReference {
	AttestationHash_t	 hash;
	OCTET_STRING_t	*content	/* OPTIONAL */;
	struct AttestationReference__location {
		A_SEQUENCE_OF(struct Location) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} location;
	struct AttestationReference__keys {
		A_SEQUENCE_OF(struct AttestationVerifierKey) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} keys;
	struct AttestationReference__revocationChecks {
		A_SEQUENCE_OF(struct RevocationCheck) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} revocationChecks;
	struct AttestationReference__extensions {
		A_SEQUENCE_OF(struct Extension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttestationReference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttestationReference;
extern asn_SEQUENCE_specifics_t asn_SPC_AttestationReference_specs_1;
extern asn_TYPE_member_t asn_MBR_AttestationReference_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Location.h"
#include "AttestationVerifierKey.h"
#include "RevocationCheck.h"
#include "Extension.h"

#endif	/* _AttestationReference_H_ */
#include <asn_internal.h>
