/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_BLS12381OAQUEKeyringBundle_H_
#define	_BLS12381OAQUEKeyringBundle_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Params-BLS12381-OAQUE.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BLS12381OAQUEBundleEntry;

/* BLS12381OAQUEKeyringBundle */
typedef struct BLS12381OAQUEKeyringBundle {
	Params_BLS12381_OAQUE_t	 params;
	struct BLS12381OAQUEKeyringBundle__entries {
		A_SEQUENCE_OF(struct BLS12381OAQUEBundleEntry) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} entries;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BLS12381OAQUEKeyringBundle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BLS12381OAQUEKeyringBundle;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BLS12381OAQUEBundleEntry.h"

#endif	/* _BLS12381OAQUEKeyringBundle_H_ */
#include <asn_internal.h>
