/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_BLS12381OAQUEBundleEntry_H_
#define	_BLS12381OAQUEBundleEntry_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Private-BLS12381-OAQUE.h"
#include <asn_SEQUENCE_OF.h>
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct BLS12381OAQUEBundleEntry__partitionChange__Member {
	long	 index;
	OCTET_STRING_t	 content;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BLS12381OAQUEBundleEntry__partitionChange__Member;

/* BLS12381OAQUEBundleEntry */
typedef struct BLS12381OAQUEBundleEntry {
	struct BLS12381OAQUEBundleEntry__partitionChange {
		A_SEQUENCE_OF(BLS12381OAQUEBundleEntry__partitionChange__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} partitionChange;
	Private_BLS12381_OAQUE_t	 key;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BLS12381OAQUEBundleEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BLS12381OAQUEBundleEntry;
extern asn_SEQUENCE_specifics_t asn_SPC_BLS12381OAQUEBundleEntry_specs_1;
extern asn_TYPE_member_t asn_MBR_BLS12381OAQUEBundleEntry_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _BLS12381OAQUEBundleEntry_H_ */
#include <asn_internal.h>
