/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EntityKeyringEntry_H_
#define	_EntityKeyringEntry_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EntityPublicKey.h"
#include "EntityPrivateKey.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EntityKeyringEntry */
typedef struct EntityKeyringEntry {
	EntityPublicKey_t	 Public;
	EntityPrivateKey_t	 secret;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EntityKeyringEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EntityKeyringEntry;
extern asn_SEQUENCE_specifics_t asn_SPC_EntityKeyringEntry_specs_1;
extern asn_TYPE_member_t asn_MBR_EntityKeyringEntry_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EntityKeyringEntry_H_ */
#include <asn_internal.h>
