/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EntityKeyring_H_
#define	_EntityKeyring_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EntityKeyringEntry;

/* EntityKeyring */
typedef struct EntityKeyring {
	struct EntityKeyring__keys {
		A_SEQUENCE_OF(struct EntityKeyringEntry) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} keys;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EntityKeyring_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EntityKeyring;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EntityKeyringEntry.h"

#endif	/* _EntityKeyring_H_ */
#include <asn_internal.h>
