/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_NameDeclarationBody_H_
#define	_NameDeclarationBody_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include "EntityHash.h"
#include "Location.h"
#include <UTCTime.h>
#include <constr_SEQUENCE.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Extension;

/* NameDeclarationBody */
typedef struct NameDeclarationBody {
	UTF8String_t	 name;
	EntityHash_t	 subject;
	Location_t	 subjectLocation;
	struct NameDeclarationBody__validity {
		UTCTime_t	 notBefore;
		UTCTime_t	 notAfter;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} validity;
	struct NameDeclarationBody__privateExtensions {
		A_SEQUENCE_OF(struct Extension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} privateExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NameDeclarationBody_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NameDeclarationBody;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Extension.h"

#endif	/* _NameDeclarationBody_H_ */
#include <asn_internal.h>
