/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RevocationCheck_H_
#define	_RevocationCheck_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EXTERNAL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RevocationCheck */
typedef EXTERNAL_t	 RevocationCheck_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RevocationCheck;
asn_struct_free_f RevocationCheck_free;
asn_struct_print_f RevocationCheck_print;
asn_constr_check_f RevocationCheck_constraint;
ber_type_decoder_f RevocationCheck_decode_ber;
der_type_encoder_f RevocationCheck_encode_der;
xer_type_decoder_f RevocationCheck_decode_xer;
xer_type_encoder_f RevocationCheck_encode_xer;
oer_type_decoder_f RevocationCheck_decode_oer;
oer_type_encoder_f RevocationCheck_encode_oer;
per_type_decoder_f RevocationCheck_decode_uper;
per_type_encoder_f RevocationCheck_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RevocationCheck_H_ */
#include <asn_internal.h>
