/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Signature_H_
#define	_Signature_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Signature */
typedef struct Signature {
	OBJECT_IDENTIFIER_t	 scheme;
	OCTET_STRING_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Signature_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Signature;

#ifdef __cplusplus
}
#endif

#endif	/* _Signature_H_ */
#include <asn_internal.h>
