/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_WaveEntitySecret_H_
#define	_WaveEntitySecret_H_


#include <asn_application.h>

/* Including external dependencies */
#include "WaveEntity.h"
#include "EXTERNAL.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* WaveEntitySecret */
typedef struct WaveEntitySecret {
	WaveEntity_t	 entity;
	EXTERNAL_t	 keyring;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WaveEntitySecret_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WaveEntitySecret;

#ifdef __cplusplus
}
#endif

#endif	/* _WaveEntitySecret_H_ */
#include <asn_internal.h>
