/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_WaveEntity_H_
#define	_WaveEntity_H_


#include <asn_application.h>

/* Including external dependencies */
#include "WaveEntityTbs.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* WaveEntity */
typedef struct WaveEntity {
	WaveEntityTbs_t	 tbs;
	OCTET_STRING_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WaveEntity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WaveEntity;
extern asn_SEQUENCE_specifics_t asn_SPC_WaveEntity_specs_1;
extern asn_TYPE_member_t asn_MBR_WaveEntity_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _WaveEntity_H_ */
#include <asn_internal.h>
