/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_WaveEncryptedMessage_H_
#define	_WaveEncryptedMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EXTERNAL;
struct Extension;

/* WaveEncryptedMessage */
typedef struct WaveEncryptedMessage {
	OCTET_STRING_t	 contents;
	struct WaveEncryptedMessage__keys {
		A_SEQUENCE_OF(struct EXTERNAL) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} keys;
	struct WaveEncryptedMessage__extensions {
		A_SEQUENCE_OF(struct Extension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WaveEncryptedMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WaveEncryptedMessage;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EXTERNAL.h"
#include "Extension.h"

#endif	/* _WaveEncryptedMessage_H_ */
#include <asn_internal.h>
