/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_WaveNameDeclaration_H_
#define	_WaveNameDeclaration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "EntityHash.h"
#include "Location.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RevocationOption;
struct Extension;
struct NameDeclarationKey;

/* WaveNameDeclaration */
typedef struct WaveNameDeclaration {
	struct WaveNameDeclaration__tbs {
		EntityHash_t	 attester;
		Location_t	 attesterLocation;
		struct WaveNameDeclaration__tbs__revocations {
			A_SEQUENCE_OF(struct RevocationOption) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} revocations;
		struct WaveNameDeclaration__tbs__publicExtensions {
			A_SEQUENCE_OF(struct Extension) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} publicExtensions;
		OCTET_STRING_t	 body;
		struct WaveNameDeclaration__tbs__keys {
			A_SEQUENCE_OF(struct NameDeclarationKey) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} keys;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} tbs;
	OCTET_STRING_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WaveNameDeclaration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WaveNameDeclaration;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RevocationOption.h"
#include "Extension.h"
#include "NameDeclarationKey.h"

#endif	/* _WaveNameDeclaration_H_ */
#include <asn_internal.h>
