/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_WaveAttestationTbs_H_
#define	_WaveAttestationTbs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EntityHash.h"
#include "Location.h"
#include "EXTERNAL.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RevocationOption;
struct Extension;

/* WaveAttestationTbs */
typedef struct WaveAttestationTbs {
	EntityHash_t	 subject;
	Location_t	 subjectLocation;
	struct WaveAttestationTbs__revocations {
		A_SEQUENCE_OF(struct RevocationOption) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} revocations;
	struct WaveAttestationTbs__publicExtensions {
		A_SEQUENCE_OF(struct Extension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} publicExtensions;
	EXTERNAL_t	 body;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WaveAttestationTbs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WaveAttestationTbs;
extern asn_SEQUENCE_specifics_t asn_SPC_WaveAttestationTbs_specs_1;
extern asn_TYPE_member_t asn_MBR_WaveAttestationTbs_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RevocationOption.h"
#include "Extension.h"

#endif	/* _WaveAttestationTbs_H_ */
#include <asn_internal.h>
