/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_WaveExplicitProof_H_
#define	_WaveExplicitProof_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AttestationReference;
struct Extension;

/* Forward definitions */
typedef struct WaveExplicitProof__paths__Member {
	A_SEQUENCE_OF(long) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WaveExplicitProof__paths__Member;

/* WaveExplicitProof */
typedef struct WaveExplicitProof {
	struct WaveExplicitProof__attestations {
		A_SEQUENCE_OF(struct AttestationReference) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} attestations;
	struct WaveExplicitProof__paths {
		A_SEQUENCE_OF(WaveExplicitProof__paths__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} paths;
	struct WaveExplicitProof__entities {
		A_SEQUENCE_OF(OCTET_STRING_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} entities;
	struct WaveExplicitProof__extensions {
		A_SEQUENCE_OF(struct Extension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WaveExplicitProof_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WaveExplicitProof;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AttestationReference.h"
#include "Extension.h"

#endif	/* _WaveExplicitProof_H_ */
#include <asn_internal.h>
