/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "WAVE-Schema"
 * 	found in "objects-lite.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_WR1VerifierBody_H_
#define	_WR1VerifierBody_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttestationVerifierBody.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* WR1VerifierBody */
typedef struct WR1VerifierBody {
	AttestationVerifierBody_t	 attestationVerifierBody;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WR1VerifierBody_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WR1VerifierBody;

#ifdef __cplusplus
}
#endif

#endif	/* _WR1VerifierBody_H_ */
#include <asn_internal.h>
